spring:
  application:
    name: dc-baika
  redis:
    cluster:
      nodes: 192.168.1.130:6311,192.168.1.131:6312,192.168.1.132:6313,192.168.1.130:6314,192.168.1.131:6315,192.168.1.132:6316
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
    timeout: 0
    password: abc123#
    commandTimeout: 5000
    maxAttempts: 30
     #------ #redis end ---------
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #------ #thymeleaf end ---------
  #dubbo
  dubbo:
    application:
      name: dc-baika-app
    #registries[0]:
      #adress: zookeeper://127.0.0.1:2181
    #registries[1]:
      #adress: zookeeper://192.168.1.117:2181
    registry:
      address: 192.168.1.130:3181,192.168.1.131:3181,192.168.1.132:3181
      protocol: zookeeper
    protocol:
      name: dubbo
    scan: com.jhh.dc.baika.app.web
    retries: 0
    qos:
      port: 22223
    consumer:
      timeout: 120000
      check: false
      retries: 0
       #------ #dubbo end ---------
  resources:
    cache-period: 0
server:
  port: 8082
  context-path: /dc-baika

swagger:
  enable: false
#md5 key
merchantKey: 123456
#格式为分钟
token:
  expire:
    time: 30
logging:
  config: classpath:logging-config.xml
ip:
  limit: 50


callback:
  baseurl: http://baika2.jhh.com